version: "3.8"

services:
  balance-calendar-generator:
    image: balance-calendar-generator
    container_name: balance-calendar-generator
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - balance-calendar-generator:/app:delegated

volumes:
  balance-calendar-generator:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}
      o: bind
